export default{
    /*PRIMARY_COLOR: '#27496D',
    PRIMARY_COLOR_DARK: '#142850',
    PRIMARY_COLOR_LIGHT: '#00909E',
    PRIMARY_COLOR_TRANSPARENT: '#DAE1E7'*/

    PRIMARY_COLOR: '#F8DA5B',
    PRIMARY_COLOR_DARK: '#247291',
    PRIMARY_COLOR_LIGHT: '#EEF2E2',
    PRIMARY_COLOR_TRANSPARENT: '#F5F9EE',
    ERROR_MESSAGE: '#FF3F00'
};